# Generated by Django 3.0.5 on 2022-04-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220430_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
            ],
        ),
    ]
