# Generated by Django 3.0.5 on 2022-04-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
