# Generated by Django 3.0.5 on 2022-05-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220501_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
    ]
