# Generated by Django 3.0.5 on 2022-05-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_tagtoapprove'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtoapprove',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='main.Scope'),
        ),
    ]
